project_id = "jktaapzaskbebwhfswth"

[functions.get-mapbox-token]
verify_jwt = false

[functions.api-integration-example]
verify_jwt = true

[functions.validate-registration-data]
verify_jwt = false

[functions.complete-registration]
verify_jwt = false