@echo off
echo Restarting Telkom Insight Hub server...
echo Stopping any running instances...
taskkill /f /im node.exe >nul 2>&1
echo Starting server...
start cmd /k "cd /d %~dp0 && node server/index.js"
echo Server restart initiated. Check the new window for logs.
pause