// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jktaapzaskbebwhfswth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprdGFhcHphc2tiZWJ3aGZzd3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjY0OTksImV4cCI6MjA2OTkwMjQ5OX0.GhFkU7k5eW8jih4v01T2M8FCqPESz3GK0qYSR-0rFOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});