name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    name: Security & Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint Security
      run: npx eslint . --ext .ts,.tsx --config eslint.config.js
      
    - name: Run TypeScript Check
      run: npx tsc --noEmit
      
    - name: Dependency Vulnerability Scan
      run: npm audit --audit-level=high
      
    - name: Run Tests
      run: npm run test
      
    - name: Code Coverage
      run: npm run test:coverage
      
    - name: Upload Coverage to CodeCov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: security-scan
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Performance Budget Check
      run: |
        BUNDLE_SIZE=$(stat -c%s "dist/assets/*.js" | awk '{sum += $1} END {print sum}')
        if [ $BUNDLE_SIZE -gt 1048576 ]; then
          echo "Bundle size exceeds 1MB limit: $BUNDLE_SIZE bytes"
          exit 1
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: dist/
        
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [security-scan, build]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-files
        path: dist/
        
    - name: Deploy to Lovable
      run: echo "Deployment handled by Lovable platform"